### ISSUE TITLE
Rpow + tests = grumpiness

### ISSUE THREAD

**Issue by eileenmcnaughton** [totten/rpow#8]
When we run unit tests with rpow enabled they fail :-(

The reason is rpow does  ``` setcookie($config['cookieName'], $value, $expires, '/');```
which results in an error of 

```Cannot modify header information - headers already sent by (output started at ....```

 Note that the UF for the tests is drupal not UNIT_TEST so we can't use that.

Is there another obvious way to detect when cookies shouldn't be set @totten

**Comment by totten** [comment]
We discussed a bit more at https://chat.civicrm.org/civicrm/pl/knpob8hdxjgm98c6khzu1xrg7a

TLDR:

1. One could skip the `setcookie() ` within tests
2. One could try to mock `setcookie()` during tests

Long-term, mocking is probably the better idea - but we're not actually testing that behavior, so near-term and mid-term, it seems OK to just skip the call to `setcookie()` well running tests.

**Comment by eileenmcnaughton** [comment]
PR at https://github.com/totten/rpow/pull/9
